name: Frontend

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

jobs:

  frontend_lint:
    name: React Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Modules
        working-directory: ./frontend
        run: npm install

      - name: Run ESLint
        working-directory: ./frontend
        run: npm run lint

  frontend_build:
    name: React Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Modules
        working-directory: ./frontend
        run: npm install

      - name: Run TSC
        working-directory: ./frontend
        run: npm run build

  frontend_lighthouse:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Modules
        working-directory: ./frontend
        run: npm install && npm install -g @lhci/cli@0.8.x && npm install -g http-server

      - name: Build Website
        working-directory: ./frontend
        run: npm run build

      - name: Generate Report
        working-directory: ./frontend
        run:
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}