name: Frontend Checks

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

jobs:

  frontend_lint:
    name: Frontend Lint Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install Modules
        working-directory: ./frontend
        run: npm install

      - name: Run ESLint & TSC
        working-directory: ./frontend
        run: npm run lint

  frontend_lighthouse:
    name: Frontend Lighthouse Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install Modules
        working-directory: ./frontend
        run: npm install && npm install -g @lhci/cli@0.8.x

      - name: Generate Report
        working-directory: ./frontend
        run: | 
          npm run build
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}