name: Frontend

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

jobs:

  frontend_lint_ts:
    name: TS Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Modules
        working-directory: ./frontend
        run: npm install

      - name: Run ESLint
        working-directory: ./frontend
        run: npm run lint-ts

  frontend_lint_html:
    name: HTML Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Modules
        working-directory: ./frontend
        run: npm install

      - name: Run HTMLHint
        working-directory: ./frontend
        run: npm run lint-html 

  frontend_lint_css:
    name: CSS Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Modules
        working-directory: ./frontend
        run: npm install

      - name: Run Stylelint
        working-directory: ./frontend
        run: npm run lint-css 

  frontend_build_ts:
    name: TS Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Modules
        working-directory: ./frontend
        run: npm install

      - name: Run TSC
        working-directory: ./frontend
        run: npm run build

  frontend_lighthouse:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Modules
        working-directory: ./frontend
        run: npm install && npm install -g @lhci/cli@0.8.x

      - name: Build Website
        working-directory: ./frontend
        run: npm run build

      - name: Generate Report
        working-directory: ./frontend
        run:
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}