name: Writing Checks

on:
  push:
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'

jobs:

  frontend_wording:
    name: Wording Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Modules
        run: npm install -g write-good cspell

      - name: Check Wording
        run: write-good *.md --no-passive

  frontend_spelling:
    name: Wording Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Modules
        run: npm install -g write-good cspell

      - name: Check Spelling
        run: cspell lint --locale en-AU "*.md" 